name: Prod Deployment

on:
  workflow_dispatch:  # manual trigger

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest test artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact
          path: dist/

      - run: echo "ðŸ”¥ Deploying to PRODUCTION environment"
      - run: cat dist/build.txt  # just to verify the artifact
